-- Fase 2: struttura relazionale. Gli snapshot restano attivi durante la
-- migrazione, quindi questa operazione non cambia il comportamento dell'app.

create table if not exists public.auctions (
  code text primary key,
  name text not null,
  budget integer not null check (budget >= 0),
  status text not null check (status in ('live', 'paused')),
  total_slots integer not null check (total_slots >= 0),
  remaining_slots integer not null check (remaining_slots >= 0),
  current_index integer not null default 0 check (current_index >= 0),
  rules jsonb not null default '{}'::jsonb,
  tier_settings jsonb not null default '[]'::jsonb,
  player_order text,
  order_by_role boolean not null default false,
  countdown_ends_at bigint,
  start_countdown_ends_at bigint,
  bid_duration_seconds integer not null default 30 check (bid_duration_seconds between 5 and 300),
  bid_countdown_ends_at bigint,
  roster_warning jsonb,
  version bigint not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.auction_participants (
  auction_code text not null references public.auctions(code) on delete cascade,
  token text not null,
  name text not null,
  role text not null check (role in ('admin', 'participant')),
  budget integer not null check (budget >= 0),
  committed integer not null default 0 check (committed >= 0),
  primary key (auction_code, token)
);

create unique index if not exists auction_participants_unique_name
  on public.auction_participants (auction_code, lower(name));

create table if not exists public.auction_players (
  auction_code text not null references public.auctions(code) on delete cascade,
  id text not null,
  sequence_index integer not null check (sequence_index >= 0),
  name text not null,
  role text not null check (role in ('POR', 'DIF', 'CEN', 'ATT')),
  team text,
  nation text,
  tier text not null,
  number text,
  quote integer not null default 0 check (quote >= 0),
  highest_bid_participant_token text,
  highest_bid_participant_name text,
  highest_bid_amount integer check (highest_bid_amount >= 0),
  primary key (auction_code, id),
  unique (auction_code, sequence_index)
);

create table if not exists public.roster_players (
  auction_code text not null,
  participant_token text not null,
  player_id text not null,
  price integer not null check (price >= 0),
  primary key (auction_code, participant_token, player_id),
  foreign key (auction_code, participant_token)
    references public.auction_participants(auction_code, token) on delete cascade,
  foreign key (auction_code, player_id)
    references public.auction_players(auction_code, id) on delete cascade
);

create table if not exists public.auction_activity (
  id bigint generated by default as identity primary key,
  auction_code text not null references public.auctions(code) on delete cascade,
  position integer not null check (position >= 0),
  name text not null,
  action text not null,
  amount integer,
  unique (auction_code, position)
);

create table if not exists public.auction_history (
  id bigint generated by default as identity primary key,
  auction_code text not null references public.auctions(code) on delete cascade,
  position integer not null check (position >= 0),
  snapshot jsonb not null,
  unique (auction_code, position)
);

create index if not exists auction_players_call_order
  on public.auction_players (auction_code, sequence_index);
create index if not exists roster_players_participant
  on public.roster_players (auction_code, participant_token);
create index if not exists auction_activity_order
  on public.auction_activity (auction_code, position);

alter table public.auctions enable row level security;
alter table public.auction_participants enable row level security;
alter table public.auction_players enable row level security;
alter table public.roster_players enable row level security;
alter table public.auction_activity enable row level security;
alter table public.auction_history enable row level security;

revoke all on public.auctions,
  public.auction_participants,
  public.auction_players,
  public.roster_players,
  public.auction_activity,
  public.auction_history
  from anon, authenticated;
