import { auctionUrl } from "../routes.js";

export function renderTierRow(tier = {}) {
  return `<fieldset class="tier-row"><label>Nome<input data-tier-name value="${tier.name || ""}" maxlength="8" required></label><label>Soglia quotazione<input data-tier-min-quote type="number" min="0" value="${tier.minQuote ?? 0}" required></label><label>Base<input data-tier-min-price type="number" min="0" value="${tier.minPrice ?? 1}" required></label><label>Rilancio<input data-tier-increment type="number" min="0" value="${tier.increment ?? 1}" required></label><label>Tetto<input data-tier-cap type="number" min="0" value="${tier.cap ?? 50}" required></label><button type="button" class="danger remove-tier">Rimuovi fascia</button></fieldset>`;
}

export function renderAdminPage(auction) {
  const tiers = (auction.tierSettings || []).filter((tier) => !tier.implicit);
  return `<div class="title-row"><div><p class="eyebrow">AMMINISTRAZIONE</p><h1>Gestisci l'<em>asta.</em></h1></div><button id="exportAll" class="ghost"><i data-lucide="download"></i> Resoconto CSV</button></div><div class="admin-card"><h2>Importa giocatori</h2><p>Carica il listone XLSX scaricato da <b>Fantacalcio.it</b>: verrà importato automaticamente solo il foglio <b>Tutti</b>. Puoi anche usare un CSV o XLSX FantaBid con le colonne <b>Nome</b>, <b>Ruolo</b>, <b>Squadra</b> e <b>Quotazione</b>; <b>Nazione</b> è facoltativa. Ogni giocatore deve comparire una sola volta.</p><input id="playerFile" type="file" accept=".csv,.xlsx"><div class="import-actions"><button id="importPlayers" class="primary">Importa catalogo <i data-lucide="upload"></i></button><span id="importLoader" class="import-loader" hidden role="status"><i data-lucide="loader-circle"></i> Caricamento…</span></div><p id="importResult" class="muted"></p></div><div class="admin-card"><h2>Fasce e regole d’asta</h2><p>Puoi rimuovere tutte le fasce: prezzo base e rilancio minimo saranno automaticamente pari a 1.</p><form id="rules"><label class="bid-duration-setting">Durata di una puntata <span><input id="bidDurationSeconds" type="number" min="5" max="300" step="1" value="${auction.bidDurationSeconds ?? 30}" required> secondi</span><small>Il timer parte all’avvio dell’asta e riparte dopo ogni offerta. “Ultima chiamata” ha sempre la precedenza.</small></label><div id="tierRows">${tiers.map(renderTierRow).join("")}</div><button type="button" id="addTier" class="ghost">+ Aggiungi fascia</button><div class="tier-actions"><button class="primary">Salva fasce e regole</button><button type="button" id="recalculateTiers" class="ghost"><i data-lucide="rotate-ccw"></i> Ricalcola fasce dei giocatori</button></div></form></div><div class="admin-card"><h2>Link di accesso</h2><p>Condividi il link partecipanti con la lega. Conserva il link amministratore in un luogo sicuro: permette di accedere alla gestione da un altro dispositivo.</p><div class="access-links"><div><small>PARTECIPANTI</small><div class="linkbox">${auctionUrl(auction.code)}<button id="copyCode">Copia</button></div></div><div><small>AMMINISTRATORE</small><div class="admin-link-actions"><button id="copyAdminLink" class="ghost">Copia link admin</button><button id="rotateAdminLink" class="danger">Rigenera link</button></div></div></div></div>`;
}
